#
# Makefile for the kernel p2pf drivers.
# $Id: Makefile 10442 2010-11-16 05:33:35Z Noguchi Isao $

# Object files in subdirectories

obj-$(CONFIG_DM)		+= dm/
obj-$(CONFIG_ZION)		+= zion/
obj-$(CONFIG_RTCTRL)	+= rtctrl/
obj-$(CONFIG_ZCOM)		+= zcom/
obj-$(CONFIG_83XXDMAC)	+= mpc83xxdmac/
obj-$(CONFIG_P2USB_BUFFER) += buffer/
obj-$(CONFIG_P2IOPORTDRV) += p2ioport/
obj-$(CONFIG_CODEC_VGA) += codec_vga/
obj-$(CONFIG_P2GPIODRV) += p2gpio/
obj-$(CONFIG_PROC_P2PF_TARGET) += p2pfinfo/
obj-$(CONFIG_PROXYDRV) += proxy/
obj-$(CONFIG_HEART_BEAT) += heartbeat/
obj-$(CONFIG_P2PF_PM) += pm/
obj-$(CONFIG_MSUDEV) += msudev/
obj-$(CONFIG_P2VERIFY) += verify/
