/*
 *  linux/include/linux/p2gpio_user.h
 *
 *   Header file of P2GPIO driver for user applications for K298
 *     
 *     Copyright (C) 2010 Panasonic, Co.,Ltd. All Rights Reserved.
 */
/* $Id: p2gpio_K298.h 10442 2010-11-16 05:33:35Z Noguchi Isao $ */

#ifndef __LINUX_P2GPIO_K298_H__
#define __LINUX_P2GPIO_K298_H__

/*
 * Number for ioctl for K298
 */
#define NR_P2GPIO_IOC_PCB_VER          0x001

/*
 * ioctl command
 */
#define P2GPIO_IOC_K298_PCB_VER             __P2GPIO_IO(K298, PCB_VER)
#define P2IOPORT_IOC_K298_PCB_VER             P2GPIO_IOC_K298_PCB_VER


//--------------------------------------------------------------------

/*
 * PORT virtual definition for K298 only
 */
#define P2GPIO_VPORT_POWER_OFF         __P2GPIO_VPORT_VALUE(K298, 0, 1)
#define P2GPIO_VPORT_BATTERY           __P2GPIO_VPORT_VALUE(K298, P2GPIO_VPORT_FLAG_RONLY, 2)
#define P2GPIO_VPORT_P2CARD_DETECT     __P2GPIO_VPORT_VALUE(K298, P2GPIO_VPORT_FLAG_RONLY, 3)
#define P2GPIO_VPORT_SSD_DETECT        __P2GPIO_VPORT_VALUE(K298, P2GPIO_VPORT_FLAG_RONLY, 4)
#define P2GPIO_VPORT_SSD_SEL_HOST      __P2GPIO_VPORT_VALUE(K298, 0, 5)
#define P2GPIO_VPORT_SSD_PON           __P2GPIO_VPORT_VALUE(K298, 0, 6)
#define P2GPIO_VPORT_SSD_OCI           __P2GPIO_VPORT_VALUE(K298, P2GPIO_VPORT_FLAG_RONLY, 7)
#define P2GPIO_VPORT_SSD_LED_SEL       __P2GPIO_VPORT_VALUE(K298, 0, 8)
#define P2GPIO_VPORT_USB_SEL_HOST      __P2GPIO_VPORT_VALUE(K298, 0, 9)
#define P2GPIO_VPORT_USB_PON           __P2GPIO_VPORT_VALUE(K298, 0, 10)
#define P2GPIO_VPORT_USB_OCI           __P2GPIO_VPORT_VALUE(K298, P2GPIO_VPORT_FLAG_RONLY, 11)

#define P2IOPORT_VPORT_POWER_OFF         P2GPIO_VPORT_POWER_OFF
#define P2IOPORT_VPORT_BATTERY           P2GPIO_VPORT_BATTERY
#define P2IOPORT_VPORT_P2CARD_DETECT     P2GPIO_VPORT_P2CARD_DETECT
#define P2IOPORT_VPORT_SSD_DETECT        P2GPIO_VPORT_SSD_DETECT
#define P2IOPORT_VPORT_SSD_SEL_HOST      P2GPIO_VPORT_SSD_SEL_HOST
#define P2IOPORT_VPORT_SSD_PON           P2GPIO_VPORT_SSD_PON
#define P2IOPORT_VPORT_SSD_OCI           P2GPIO_VPORT_SSD_OCI
#define P2IOPORT_VPORT_SSD_LED_SEL       P2GPIO_VPORT_SSD_LED_SEL
#define P2IOPORT_VPORT_USB_SEL_HOST      P2GPIO_VPORT_USB_SEL_HOST
#define P2IOPORT_VPORT_USB_PON           P2GPIO_VPORT_USB_PON
#define P2IOPORT_VPORT_USB_OCI           P2GPIO_VPORT_USB_OCI


#endif /* __LINUX_P2GPIO_K298_H__ */
