/*
 *  linux/include/linux/p2gpio_user.h
 *
 *   Header file of P2GPIO driver for user applications for K318
 *     
 *     Copyright (C) 2010 Panasonic, Co.,Ltd. All Rights Reserved.
 */
/* $Id: p2gpio_K318.h 21116 2012-04-25 06:59:44Z Yoshioka Masaki $ */

#ifndef __LINUX_P2GPIO_K318_H__
#define __LINUX_P2GPIO_K318_H__


/*
 * PORT virtual definition for K318 only
 */

/* USB */
#define P2GPIO_VPORT_VBUS_USBHOST       __P2GPIO_VPORT_VALUE(K318, 0, 0x01)
#define P2GPIO_VPORT_USB_OCI            __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x03)

#define P2GPIO_VPORT_VBUS_USBHOST2      __P2GPIO_VPORT_VALUE(K318, 0, 0x04)
#define P2GPIO_VPORT_USB_OCI2           __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x05)

#define P2GPIO_VPORT_USB_HOST           __P2GPIO_VPORT_VALUE(K318, 0, 0x06)
#define P2GPIO_VPORT_USB_OE             __P2GPIO_VPORT_VALUE(K318, 0, 0x07)
#define P2GPIO_VPORT_USB_HUB            __P2GPIO_VPORT_VALUE(K318, 0, 0x08)

/* JTAG */
#define P2GPIO_VPORT_JTAG_TDO           __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x10)
#define P2GPIO_VPORT_JTAG_TDI           __P2GPIO_VPORT_VALUE(K318, 0, 0x11)
#define P2GPIO_VPORT_JTAG_TMS           __P2GPIO_VPORT_VALUE(K318, 0, 0x12)
#define P2GPIO_VPORT_JTAG_TCK           __P2GPIO_VPORT_VALUE(K318, 0, 0x13)

#define P2IOPORT_VPORT_JTAG_TDO         P2GPIO_VPORT_JTAG_TDO
#define P2IOPORT_VPORT_JTAG_TDI         P2GPIO_VPORT_JTAG_TDI
#define P2IOPORT_VPORT_JTAG_TMS         P2GPIO_VPORT_JTAG_TMS
#define P2IOPORT_VPORT_JTAG_TCK         P2GPIO_VPORT_JTAG_TCK

#define P2IOPORT_VPORT_SPI_SO           P2GPIO_VPORT_JTAG_TDO
#define P2IOPORT_VPORT_SPI_SI           P2GPIO_VPORT_JTAG_TDI
#define P2IOPORT_VPORT_SPI_CS           P2GPIO_VPORT_JTAG_TMS
#define P2IOPORT_VPORT_SPI_CK           P2GPIO_VPORT_JTAG_TCK

/* PROXY */
#define P2GPIO_VPORT_PROXY_DETECTION    __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x20)
#define P2GPIO_VPORT_PROXY_TGT_RST      __P2GPIO_VPORT_VALUE(K318, 0, 0x21)
#define P2GPIO_VPORT_PROXY_DSP          __P2GPIO_VPORT_VALUE(K318, 0, 0x22)
#define P2GPIO_VPORT_PROXY_FPGA         __P2GPIO_VPORT_VALUE(K318, 0, 0x23)

#define P2IOPORT_VPORT_JTAG_PXY_DSP     P2GPIO_VPORT_PROXY_DSP
#define P2IOPORT_VPORT_JTAG_PXY_FPGA    P2GPIO_VPORT_PROXY_FPGA

/* EVF */
#define P2GPIO_VPORT_EVF_DETECTION      __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x30)
#define P2GPIO_VPORT_EVF_SPI            __P2GPIO_VPORT_VALUE(K318, 0, 0x31)

#define P2IOPORT_VPORT_EVF_SPI          P2GPIO_VPORT_EVF_SPI

/* SDI_IN */
#define P2GPIO_VPORT_SDI_DETECTION      __P2GPIO_VPORT_VALUE(K318, P2GPIO_VPORT_FLAG_RONLY, 0x40)
#define P2GPIO_VPORT_SDI_SPI            __P2GPIO_VPORT_VALUE(K318, 0, 0x41)

#define P2IOPORT_VPORT_SDI_SPI          P2GPIO_VPORT_SDI_SPI

/* VUP_STATUS */
#define P2GPIO_VPORT_VUP_STS_BLINK      __P2GPIO_VPORT_VALUE(K318, 0, 0x50)
#define P2GPIO_VPORT_VUP_STS_ERROR      __P2GPIO_VPORT_VALUE(K318, 0, 0x51)
#define P2GPIO_VPORT_VUP_STS_FINISH     __P2GPIO_VPORT_VALUE(K318, 0, 0x52)
#define P2GPIO_VPORT_VUP_STS_BIGIN      __P2GPIO_VPORT_VALUE(K318, 0, 0x53)

#endif /* __LINUX_P2GPIO_K318_H__ */

