/*
 *  linux/include/linux/p2gpio_user.h
 *
 *   Header file of P2GPIO driver for user applications
 *     
 *     Copyright (C) 2010 Panasonic, Co.,Ltd. All Rights Reserved.
 */
/* $Id: p2gpio_user.h 20439 2012-04-04 04:46:39Z Yoshioka Masaki $ */

#ifndef __LINUX_P2GPIO_USER_H__
#define __LINUX_P2GPIO_USER_H__

#include <asm/ioctl.h>

/*
 * structures
 */

struct p2gpio_val_s
{
  int num;           /* [in] the number of device(DIPSW, LED...) */
  unsigned long val; /* [in/out] value */
};
#define p2ioport_val_s p2gpio_val_s


/*
 * @ _dir : _IOC_NONE, _IOC_READ, _IOC_WRITE
 * @ _machine : COMMON or Kxxx (Kxxx -> K298, K302, ...)
 * @ _nr : number
 * @ _size : size
 */
#define __P2GPIO_IOC(_dir, _machine, _nr, size)                     \
    _IOC(_dir, P2GPIO_IOC_MAGIC_##_machine, NR_P2GPIO_IOC_##_nr, size)
#define __P2GPIO_IO(_machine, _nr)                          \
    _IO(P2GPIO_IOC_MAGIC_##_machine, NR_P2GPIO_IOC_##_nr)
#define __P2GPIO_IOR(_machine, _nr, size)                           \
    _IOR(P2GPIO_IOC_MAGIC_##_machine, NR_P2GPIO_IOC_##_nr, size)
#define __P2GPIO_IOW(_machine, _nr, size)                           \
    _IOW(P2GPIO_IOC_MAGIC_##_machine, NR_P2GPIO_IOC_##_nr, size)
#define __P2GPIO_IOWR(_machine, _nr, size)                          \
    _IOWR(P2GPIO_IOC_MAGIC_##_machine, NR_P2GPIO_IOC_##_nr, size)


#define __P2GPIO_VPORT_VALUE(machine, flags, id) \
    ((((flags)&0x7F)<<24) |                      \
    ((P2GPIO_IOC_MAGIC_##machine)<<16) |        \
     (((id)&0xffff)<<0))
#define P2GPIO_VPORT_FLAG_RONLY  (1<<0)      /* read-only */
#define P2GPIO_VPORT_FLAG_REVERSE (1<<1)     /* reverse polarity */


/*
 * Magic number for ioctl
 */
#define P2GPIO_IOC_MAGIC_COMMON     0xD0 /* COMMON */
#define P2GPIO_IOC_MAGIC_OLD        0xD1 /* OLD */
#define P2GPIO_IOC_MAGIC_K298       0xD2 /* K298 */
#define P2GPIO_IOC_MAGIC_K302       0xD3 /* K302 */
#define P2GPIO_IOC_MAGIC_K301       0xD4 /* K301 */
#define P2GPIO_IOC_MAGIC_K283       0xD5 /* K283 */
#define P2GPIO_IOC_MAGIC_K318       0xD6 /* K318 */

/*
 * Number for ioctl
 */
#define NR_P2GPIO_IOC_GET_DIPSW     0
#define NR_P2GPIO_IOC_GET_LED       1
#define NR_P2GPIO_IOC_SET_LED       2
#define NR_P2GPIO_IOC_CLR_LED       3
#define NR_P2GPIO_IOC_TOGGLE_LED    4
#define NR_P2GPIO_IOC_GET_VPORT     5
#define NR_P2GPIO_IOC_SET_VPORT     6
#define NR_P2GPIO_IOC_LOCK_VPORT    7
#define NR_P2GPIO_IOC_UNLOCK_VPORT  8
#define NR_P2GPIO_IOC_VPORT_BY_NAME     9
#define NR_P2GPIO_IOC_GET_VPORT_NAME    10
#define NR_P2GPIO_IOC_GET_ROTSW     11


/*
 * ioctl command
 */

#define P2GPIO_IOC_GET_DIPSW    __P2GPIO_IOWR(COMMON, GET_DIPSW, struct p2gpio_val_s)
#define P2IOPORT_IOC_GET_DIPSW    P2GPIO_IOC_GET_DIPSW

#define P2GPIO_IOC_GET_ROTSW    __P2GPIO_IOWR(COMMON, GET_ROTSW, struct p2gpio_val_s)
#define P2IOPORT_IOC_GET_ROTARYSW    P2GPIO_IOC_GET_ROTSW

#define P2GPIO_IOC_GET_LED      __P2GPIO_IOWR(COMMON, GET_LED, struct p2gpio_val_s)
#define P2IOPORT_IOC_GET_LED      P2GPIO_IOC_GET_LED

#define P2GPIO_IOC_SET_LED      __P2GPIO_IOW(COMMON, SET_LED, struct p2gpio_val_s)
#define P2IOPORT_IOC_SET_LED    __P2GPIO_IOW(OLD, SET_LED, struct p2gpio_val_s)

#define P2GPIO_IOC_CLR_LED      __P2GPIO_IOW(COMMON, CLR_LED, struct p2gpio_val_s)
#define P2IOPORT_IOC_CLR_LED    __P2GPIO_IOW(OLD, CLR_LED, int)

#define P2GPIO_IOC_TOGGLE_LED   __P2GPIO_IOW(COMMON, TOGGLE_LED, struct p2gpio_val_s)
#define P2IOPORT_IOC_TOGGLE_LED   P2GPIO_IOC_TOGGLE_LED

#define P2GPIO_IOC_GET_VPORT	__P2GPIO_IOWR(COMMON, GET_VPORT, struct p2gpio_val_s)
#define P2IOPORT_IOC_GET_VPORT      P2GPIO_IOC_GET_VPORT

#define P2GPIO_IOC_SET_VPORT	__P2GPIO_IOW(COMMON, SET_VPORT, struct p2gpio_val_s)
#define P2IOPORT_IOC_SET_VPORT	P2GPIO_IOC_SET_VPORT

#define P2GPIO_IOC_LOCK_VPORT   __P2GPIO_IOWR(COMMON, LOCK_VPORT, struct p2gpio_val_s)
#define P2IOPORT_IOC_LOCK_VPORT   P2GPIO_IOC_LOCK_VPORT

#define P2GPIO_IOC_UNLOCK_VPORT __P2GPIO_IOW(COMMON, UNLOCK_VPORT, struct p2gpio_val_s)
#define P2IOPORT_IOC_UNLOCK_VPORT P2GPIO_IOC_UNLOCK_VPORT

#define P2GPIO_IOC_VPORT_BY_NAME    __P2GPIO_IOWR(COMMON, VPORT_BY_NAME, struct p2ioport_val_s)

#define P2GPIO_IOC_GET_VPORT_NAME(idx)    __P2GPIO_IOC( _IOC_READ|_IOC_WRITE, COMMON, GET_VPORT_NAME, idx)


/*
 * PORT virtual port definition (COMMON)
 */

/* misc */
#define P2GPIO_VPORT_SDLED          __P2GPIO_VPORT_VALUE(COMMON, 0, 0x001)
#define P2GPIO_VPORT_RST_RICOH      __P2GPIO_VPORT_VALUE(COMMON, 0, 0x002)
#define P2GPIO_VPORT_ZION_INIT_L    __P2GPIO_VPORT_VALUE(COMMON, \
                                                         P2GPIO_VPORT_FLAG_REVERSE | P2GPIO_VPORT_FLAG_RONLY, \
                                                         0x003)
#define P2GPIO_VPORT_PCIE_SSC_ON    __P2GPIO_VPORT_VALUE(COMMON, 0, 0x04)

#define P2GPIO_VPORT_PCB_VER0       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x010)
#define P2GPIO_VPORT_PCB_VER1       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x011)

#define P2GPIO_VPORT_SYSCON_RST     __P2GPIO_VPORT_VALUE(COMMON, 0, 0x18)
#define P2GPIO_VPORT_SYSCON_W       __P2GPIO_VPORT_VALUE(COMMON, 0, 0x19)
#define P2GPIO_VPORT_CAMSYS_RST     __P2GPIO_VPORT_VALUE(COMMON, 0, 0x1A)
#define P2GPIO_VPORT_CAMSYS_W       __P2GPIO_VPORT_VALUE(COMMON, 0, 0x1B)
#define P2GPIO_VPORT_VUP_MODE       __P2GPIO_VPORT_VALUE(COMMON, 0, 0x1C)

#define P2IOPORT_VPORT_SDLED        P2GPIO_VPORT_SDLED
#define P2IOPORT_VPORT_RST_RICOH    P2GPIO_VPORT_RST_RICOH
#define P2IOPORT_VPORT_ZION_INIT_L  P2GPIO_VPORT_ZION_INIT_L
#define P2IOPORT_VPORT_PCB_VER0     P2GPIO_VPORT_PCB_VER0
#define P2IOPORT_VPORT_PCB_VER1     P2GPIO_VPORT_PCB_VER1

#define P2IOPORT_VPORT_SYSCON_RST   P2GPIO_VPORT_SYSCON_RST
#define P2IOPORT_VPORT_SYSCON_W     P2GPIO_VPORT_SYSCON_W
#define P2IOPORT_VPORT_CAM_RST      P2GPIO_VPORT_CAMSYS_RST
#define P2IOPORT_VPORT_CAM_W        P2GPIO_VPORT_CAMSYS_W
#define P2IOPORT_VPORT_VUP_MODE     P2GPIO_VPORT_VUP_MODE


/* FPGA configration */
#define P2GPIO_VPORT_FPGA_CONFDONE  __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x021)
#define P2GPIO_VPORT_FPGA_NCONFIG   __P2GPIO_VPORT_VALUE(COMMON, 0, 0x022)
#define P2GPIO_VPORT_FPGA_NSTATUS   __P2GPIO_VPORT_VALUE(COMMON, 0, 0x023)
#define P2GPIO_VPORT_FPGA_INITDONE  __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x024)

#define P2IOPORT_VPORT_FPGA_CONFDONE  P2GPIO_VPORT_FPGA_CONFDONE
#define P2IOPORT_VPORT_FPGA_NCONFIG   P2GPIO_VPORT_FPGA_NCONFIG
#define P2IOPORT_VPORT_FPGA_NSTATUS   P2GPIO_VPORT_FPGA_NSTATUS
#define P2IOPORT_VPORT_FPGA_INITDONE  P2GPIO_VPORT_FPGA_INITDONE


/* SPI by GPIO */
#define P2GPIO_VPORT_SPI_CS0  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x030)
#define P2GPIO_VPORT_SPI_CS1  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x031)
#define P2GPIO_VPORT_SPI_CS2  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x032)
#define P2GPIO_VPORT_SPI_CS3  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x033)
#define P2GPIO_VPORT_SPI_CS4  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x034)
#define P2GPIO_VPORT_SPI_CS5  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x035)
#define P2GPIO_VPORT_SPI_CS6  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x036)
#define P2GPIO_VPORT_SPI_CS7  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x037)
#define P2GPIO_VPORT_SPI_CLK  __P2GPIO_VPORT_VALUE(COMMON, 0, 0x038)
#define P2GPIO_VPORT_SPI_DOUT __P2GPIO_VPORT_VALUE(COMMON, 0, 0x039)
#define P2GPIO_VPORT_SPI_DIN  __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x040)

#define P2GPIO_VPORT_USB3_SPI_SEL       __P2GPIO_VPORT_VALUE(COMMON, 0, 0x48)


/* ROTSW */
#define P2GPIO_VPORT_ROTSW_0           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x60)
#define P2GPIO_VPORT_ROTSW_1           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x61)
#define P2GPIO_VPORT_ROTSW_2           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x62)
#define P2GPIO_VPORT_ROTSW_3           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x63)
#define P2GPIO_VPORT_ROTSW_4           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x64)
#define P2GPIO_VPORT_ROTSW_5           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x65)
#define P2GPIO_VPORT_ROTSW_6           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x66)
#define P2GPIO_VPORT_ROTSW_7           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x67)
#define P2GPIO_VPORT_ROTSW_8           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x68)
#define P2GPIO_VPORT_ROTSW_9           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x69)
#define P2GPIO_VPORT_ROTSW_10          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6A)
#define P2GPIO_VPORT_ROTSW_11          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6B)
#define P2GPIO_VPORT_ROTSW_12          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6C)
#define P2GPIO_VPORT_ROTSW_13          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6D)
#define P2GPIO_VPORT_ROTSW_14          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6E)
#define P2GPIO_VPORT_ROTSW_15          __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x6F)

#define P2IOPORT_VPORT_ROTARYSW_0    P2GPIO_VPORT_ROTSW_0
#define P2IOPORT_VPORT_ROTARYSW_1    P2GPIO_VPORT_ROTSW_1
#define P2IOPORT_VPORT_ROTARYSW_2    P2GPIO_VPORT_ROTSW_2
#define P2IOPORT_VPORT_ROTARYSW_3    P2GPIO_VPORT_ROTSW_3
#define P2IOPORT_VPORT_ROTARYSW_4    P2GPIO_VPORT_ROTSW_4
#define P2IOPORT_VPORT_ROTARYSW_5    P2GPIO_VPORT_ROTSW_5
#define P2IOPORT_VPORT_ROTARYSW_6    P2GPIO_VPORT_ROTSW_6
#define P2IOPORT_VPORT_ROTARYSW_7    P2GPIO_VPORT_ROTSW_7
#define P2IOPORT_VPORT_ROTARYSW_8    P2GPIO_VPORT_ROTSW_8
#define P2IOPORT_VPORT_ROTARYSW_9    P2GPIO_VPORT_ROTSW_9
#define P2IOPORT_VPORT_ROTARYSW_10   P2GPIO_VPORT_ROTSW_10
#define P2IOPORT_VPORT_ROTARYSW_11   P2GPIO_VPORT_ROTSW_11
#define P2IOPORT_VPORT_ROTARYSW_12   P2GPIO_VPORT_ROTSW_12
#define P2IOPORT_VPORT_ROTARYSW_13   P2GPIO_VPORT_ROTSW_13
#define P2IOPORT_VPORT_ROTARYSW_14   P2GPIO_VPORT_ROTSW_14
#define P2IOPORT_VPORT_ROTARYSW_15   P2GPIO_VPORT_ROTSW_15


/* DIPSW */
#define P2GPIO_VPORT_DIPSW_0           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x80)
#define P2GPIO_VPORT_DIPSW_1           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x81)
#define P2GPIO_VPORT_DIPSW_2           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x82)
#define P2GPIO_VPORT_DIPSW_3           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x83)
#define P2GPIO_VPORT_DIPSW_4           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x84)
#define P2GPIO_VPORT_DIPSW_5           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x85)
#define P2GPIO_VPORT_DIPSW_6           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x86)
#define P2GPIO_VPORT_DIPSW_7           __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0x87)

#define P2IOPORT_VPORT_DIPSW_0    P2GPIO_VPORT_DIPSW_0
#define P2IOPORT_VPORT_DIPSW_1    P2GPIO_VPORT_DIPSW_1
#define P2IOPORT_VPORT_DIPSW_2    P2GPIO_VPORT_DIPSW_2
#define P2IOPORT_VPORT_DIPSW_3    P2GPIO_VPORT_DIPSW_3
#define P2IOPORT_VPORT_DIPSW_4    P2GPIO_VPORT_DIPSW_4
#define P2IOPORT_VPORT_DIPSW_5    P2GPIO_VPORT_DIPSW_5
#define P2IOPORT_VPORT_DIPSW_6    P2GPIO_VPORT_DIPSW_6
#define P2IOPORT_VPORT_DIPSW_7    P2GPIO_VPORT_DIPSW_7


/* LED */
#define P2GPIO_VPORT_LED_0             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA0)
#define P2GPIO_VPORT_LED_1             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA1)
#define P2GPIO_VPORT_LED_2             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA2)
#define P2GPIO_VPORT_LED_3             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA3)
#define P2GPIO_VPORT_LED_4             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA4)
#define P2GPIO_VPORT_LED_5             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA5)
#define P2GPIO_VPORT_LED_6             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA6)
#define P2GPIO_VPORT_LED_7             __P2GPIO_VPORT_VALUE(COMMON, 0, 0xA7)

#define P2IOPORT_VPORT_LED_0    P2GPIO_VPORT_LED_0
#define P2IOPORT_VPORT_LED_1    P2GPIO_VPORT_LED_1
#define P2IOPORT_VPORT_LED_2    P2GPIO_VPORT_LED_2
#define P2IOPORT_VPORT_LED_3    P2GPIO_VPORT_LED_3
#define P2IOPORT_VPORT_LED_4    P2GPIO_VPORT_LED_4
#define P2IOPORT_VPORT_LED_5    P2GPIO_VPORT_LED_5
#define P2IOPORT_VPORT_LED_6    P2GPIO_VPORT_LED_6
#define P2IOPORT_VPORT_LED_7    P2GPIO_VPORT_LED_7


/* TEST Port */
#define P2GPIO_VPORT_TESTP_0           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC0)
#define P2GPIO_VPORT_TESTP_1           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC1)
#define P2GPIO_VPORT_TESTP_2           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC2)
#define P2GPIO_VPORT_TESTP_3           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC3)
#define P2GPIO_VPORT_TESTP_4           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC4)
#define P2GPIO_VPORT_TESTP_5           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC5)
#define P2GPIO_VPORT_TESTP_6           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC6)
#define P2GPIO_VPORT_TESTP_7           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC7)
#define P2GPIO_VPORT_TESTP_8           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC8)
#define P2GPIO_VPORT_TESTP_9           __P2GPIO_VPORT_VALUE(COMMON, 0, 0xC9)
#define P2GPIO_VPORT_TESTP_10          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCA)
#define P2GPIO_VPORT_TESTP_11          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCB)
#define P2GPIO_VPORT_TESTP_12          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCC)
#define P2GPIO_VPORT_TESTP_13          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCD)
#define P2GPIO_VPORT_TESTP_14          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCE)
#define P2GPIO_VPORT_TESTP_15          __P2GPIO_VPORT_VALUE(COMMON, 0, 0xCF)

#define P2IOPORTRT_TESTP_0      P2GPIO_VPORT_TESTP_0
#define P2IOPORTRT_TESTP_1      P2GPIO_VPORT_TESTP_1
#define P2IOPORTRT_TESTP_2      P2GPIO_VPORT_TESTP_2
#define P2IOPORTRT_TESTP_3      P2GPIO_VPORT_TESTP_3
#define P2IOPORTRT_TESTP_4      P2GPIO_VPORT_TESTP_4
#define P2IOPORTRT_TESTP_5      P2GPIO_VPORT_TESTP_5
#define P2IOPORTRT_TESTP_6      P2GPIO_VPORT_TESTP_6
#define P2IOPORTRT_TESTP_7      P2GPIO_VPORT_TESTP_7
#define P2IOPORTRT_TESTP_8      P2GPIO_VPORT_TESTP_8
#define P2IOPORTRT_TESTP_9      P2GPIO_VPORT_TESTP_9
#define P2IOPORTRT_TESTP_10     P2GPIO_VPORT_TESTP_10
#define P2IOPORTRT_TESTP_11     P2GPIO_VPORT_TESTP_11
#define P2IOPORTRT_TESTP_12     P2GPIO_VPORT_TESTP_12
#define P2IOPORTRT_TESTP_13     P2GPIO_VPORT_TESTP_13
#define P2IOPORTRT_TESTP_14     P2GPIO_VPORT_TESTP_14
#define P2IOPORTRT_TESTP_15     P2GPIO_VPORT_TESTP_15

/* PC_MODE */
#define P2GPIO_VPORT_PC_MODE0       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0xD0)
#define P2GPIO_VPORT_PC_MODE1       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0xD1)
#define P2GPIO_VPORT_PC_MODE2       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0xD2)
#define P2GPIO_VPORT_PC_MODE3       __P2GPIO_VPORT_VALUE(COMMON, P2GPIO_VPORT_FLAG_RONLY, 0xD3)

#define P2IOPORT_VPORT_PC_MODE0     P2GPIO_VPORT_PC_MODE0
#define P2IOPORT_VPORT_PC_MODE1     P2GPIO_VPORT_PC_MODE1
#define P2IOPORT_VPORT_PC_MODE2     P2GPIO_VPORT_PC_MODE2
#define P2IOPORT_VPORT_PC_MODE3     P2GPIO_VPORT_PC_MODE3

/** [[for P2V3]] include machine-depended header file. **/









#endif /* __LINUX_P2GPIO_USER_H__ */

/******************** the end of the file "p2gpio_user.h" ********************/
