#
# drivers/p2pf/pm/Makefile
# Makefile for pm
# $Id: Makefile 5088 2010-02-09 02:49:16Z Sawada Koji $
#

## power-off control
obj-$(CONFIG_P2PF_PM)	+= pm.o
pm-$(CONFIG_P2PF_PM_POFF)	+= poff.o
pm-$(CONFIG_P2PF_PM_POFF_GPIO) += poff_gpio.o
