#
# Makefile for the P2MSU device drivers.
# $Id: Makefile 5608 2010-03-09 08:03:31Z Noguchi Isao $

# Object files in subdirectories

obj-$(CONFIG_MSUDEV_ADC)	+= adc/
obj-$(CONFIG_MSUDEV_KEYEV)	+= keyev/
obj-$(CONFIG_MSUDEV_LED)	+= led/
obj-$(CONFIG_MSUDEV_BUZZER)	+= buzzer/
