#ifndef __ZION_NEOCTRL_REGS_H__
#define __ZION_NEOCTRL_REGS_H__

#define NEOCTRL_INTERRUPT_CLEAR    (0x083A)
#define NEOCTRL_INTERRUPT_STATUS_A (0x083C)
#define NEOCTRL_INTERRUPT_MASK_A   (0x083E)

#endif /* __ZION_NEOCTRL_REGS_H__ */
